server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Явный fallback для роутов вида /blocks/:id при прямом переходе по ссылке
    location /blocks/ {
        try_files $uri $uri/ /index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
